### ISSUE TITLE
bull-board 6.20.0 introduced hard dependency to bullmq

### ISSUE THREAD

**Issue by am-burban** [felixmosh/bull-board#1088]
Hello there!

After updating bull-board to v6.20.2 in our application we noticed the following error:

```
Error: Cannot find module 'bullmq'
Require stack:
- node_modules/.pnpm/@bull-board+api@6.20.2_@bull-board+ui@6.20.2/node_modules/@bull-board/api/dist/providers/flow.js
- node_modules/.pnpm/@bull-board+api@6.20.2_@bull-board+ui@6.20.2/node_modules/@bull-board/api/dist/handlers/jobFlow.js
- node_modules/.pnpm/@bull-board+api@6.20.2_@bull-board+ui@6.20.2/node_modules/@bull-board/api/dist/routes.js
- node_modules/.pnpm/@bull-board+api@6.20.2_@bull-board+ui@6.20.2/node_modules/@bull-board/api/dist/index.js
- [redacted]
```

This seems to have been caused by the recent addition of the job flow tree visualization, which is unconditionally imported into the routes. It seems we cannot work around that, since we're only importing `createBullBoard` from `@bull-board/api` and that automatically imports the routes.
Since bull-board wants to be compatible with both, bull and bullmq, it would be great if you could remove this hard dependency for bullmq.

Thanks!

**Comment by felixmosh** [comment]
@IbrahimMohammed47 can you look at this?
